openapi: 3.0.1
info:
  title: TNBC Triple Negative Cell Segmentation 
  version: 1.0.0
  description: Web App for Triple Negative Cell Segmentation research
# servers:
#   - url: url
#     description: Production server
paths:
  /coordinates/{imageId}:
    get:
      operationId: coordinatesGet
      tags:
        - Coordinates
      summary: Get coordinates of the segments on each image
      parameters:
        - name: imageId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  coordinates:
                    type: object
                    additionalProperties: false
                    properties:
                      something: 
                        type: string
  /images:
    get:
      operationId: imagesGet
      tags:
        - Images
      summary: Get three images to assess
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  schema:
                    type: object
                    additionalProperties: false
                    properties:
                      imageId: 
                        type: string
                      url:
                        type: string
                      coors:
                        type: string 
      security:
        - bearerAuth: []
  /images-annotation-selection/{imageId}:
    patch:
      operationId: imagesAnnotationSelection
      tags:
        - Images Annotation Selection
      summary: Submit the results of best annotation from client
      parameters:
        - name: imageId
          in: path
          description: Image Id to patch
          required: true
          schema:
            type: string
        - name: coorId
          in: query
          description: Coordinate Id to patch
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK     
      security:
        - bearerAuth: []       
  /login:
    post:
      operationId: login
      tags:
        - Auth
      summary: Allow user to log in
      requestBody:
        description: Username and password
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              required:
                - idToken
              properties:
                idToken:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  accessToken:
                    type: string
components:
  securitySchemes:
    bearerAuth:           
      type: http
      scheme: bearer
      bearerFormat: JWT   


                
                
        
